modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="ravagecabbage" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ravage & Cabbage" #mandatory
credits="Thanks to Leatherboots Larry, and everyone who contributed these amazing ideas which started the mod!" #optional
authors="Coda" #optional
description='''
Ravage & Cabbage is a mod that adds cabbage and some new things to ravagers!
'''
